import Head from "next/head";
import Hero from "../components/WebPages/Hero";
import Page2 from "../components/WebPages/Page2";
import Page3 from "../components/WebPages/Page3";
import Imagecards from "../components/Cards/Imagecards";

export default function Home() {
  return (
    <div>
      <Head>
        <link href="//db.onlinewebfonts.com/c/1868e326d3ee28e5395f6efa2bc037bf?family=Eina01-Regular" rel="stylesheet" type="text/css"/>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative m-">
      <Hero />
      <Page2/>
      <Page3/>
      </div>
    </div>
  );
}
